// Module2_FrontendDev/handson_06/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useContext } from "react";
import { EnrollmentContext } from "../context/EnrollmentContext";

function Header({ siteName }) {
  const { enrolledCourses } = useContext(EnrollmentContext);

  return (
    <header className="header">
      <h1>{siteName}</h1>

      <nav>
        <ul className="nav-links">
          <li>
            <Link to="/">Home</Link>
          </li>

          <li>
            <Link to="/courses">Courses</Link>
          </li>

          <li>
            <Link to="/profile">Profile</Link>
          </li>
        </ul>
      </nav>

      <div className="enrolled">
        <strong>Enrolled:</strong> {enrolledCourses.length}
      </div>
    </header>
  );
}

export default Header;

// Module2_FrontendDev/student-portal-vue/src/components/Header.vue
<template>
  <header>
    <h1>Student Portal</h1>

    <nav>
      <RouterLink to="/">Home</RouterLink> |
      <RouterLink to="/courses">Courses</RouterLink> |
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>

    <hr />
  </header>
</template>

<script setup>
import { RouterLink } from "vue-router";
</script>

<style scoped>
header {
  padding: 15px;
}
</style>
