// Module2_FrontendDev/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="card">
    <h3>{{ name }}</h3>

    <p><strong>Code:</strong> {{ code }}</p>

    <p><strong>Credits:</strong> {{ credits }}</p>

    <p><strong>Grade:</strong> {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String,
});
</script>

<style scoped>
.card {
  border: 1px solid gray;
  padding: 15px;
  margin: 10px;
}
</style>

// Module2_FrontendDev/handson_05/src/components/CourseCard.jsx
function CourseCard({
  id,
  name,
  code,
  credits,
  grade,
  onEnroll
}) {
  return (
    <div className="course-card">

      <h3>{name}</h3>

      <p><strong>Code:</strong> {code}</p>

      <p><strong>Credits:</strong> {credits}</p>

      <p><strong>Grade:</strong> {grade}</p>

      <button onClick={() => onEnroll(id)}>
        Enroll
      </button>

    </div>
  );
}

export default CourseCard;
