// Module2_FrontendDev/student-portal-vue/src/components/Header.vue
<template>
  <header>
    <h1>Student Portal</h1>

    <nav>
      <RouterLink to="/">Home</RouterLink> |
      <RouterLink to="/courses">Courses</RouterLink> |
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>

    <hr />
  </header>
</template>

<script setup>
import { RouterLink } from "vue-router";
</script>

<style scoped>
header {
  padding: 15px;
}
</style>

// Module2_FrontendDev/handson_05/src/components/Header.jsx
function Header({ siteName, enrolledCount }) {
  return (
    <header className="header">
      <h1>{siteName}</h1>

      <nav>
        <ul className="nav-links">
          <li>Home</li>
          <li>Courses</li>
          <li>Profile</li>
        </ul>
      </nav>

      <div className="enrolled">
        <strong>Enrolled:</strong> {enrolledCount}
      </div>
    </header>
  );
}

export default Header;
